/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quick.hotel;

import com.toedter.calendar.JDateChooser;
import static java.lang.Thread.sleep;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static quick.hotel.Conexion.clave;
import static quick.hotel.Login.CampoUsuario;

/**
 *
 * @author ALIENWARE
 */
public class Registro extends javax.swing.JFrame {

    private TimeZone tz;

    /**
     * Creates new form registro
     */
    public Registro() {
        initComponents();
        cargar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        combo_IDENTIDAD = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        campo_pri_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campo_seg_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campo_cel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campocorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo_identificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campo_pri_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campo_seg_apellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campo_tel = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        btncrear = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        campo_calendario = new com.toedter.calendar.JDateChooser();
        combopais = new javax.swing.JComboBox<>();
        combodpto = new javax.swing.JComboBox<>();
        combociudad = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        campo_direccion = new javax.swing.JTextField();
        Lfecha_naci = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tipo De Identificacion:(*)");

        combo_IDENTIDAD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combo_IDENTIDAD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "CC", "TI", "PPORTE", "CC_EXTRAN" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Primer Nombres:(*)");

        campo_pri_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_pri_nombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Segundo Nombre:(*)");

        campo_seg_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_seg_nombreActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Celular:(*)");

        campo_cel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_celActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Correo:(*)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Direccion:(*)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Identidicacion:(*)");

        campo_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_identificacionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Primer Apellido:(*)");

        campo_pri_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_pri_apellidoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Segundo Apellido:(*)");

        campo_seg_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_seg_apellidoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefono:(*)");

        campo_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_telActionPerformed(evt);
            }
        });

        btnlimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/limpiar.png"))); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btncrear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/crear.png"))); // NOI18N
        btncrear.setText("CREAR  HUESPED");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Fecha_Naci:(*)");

        campo_calendario.setDateFormatString("dd/MMM/yyyy");
        campo_calendario.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        combopais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        combopais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopaisActionPerformed(evt);
            }
        });

        combodpto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        combodpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodptoActionPerformed(evt);
            }
        });

        combociudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        combociudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combociudadActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("REGISTRO DE CRUD HUESPED");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Pais:(*)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Departamento:(*)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("ciudad:(*)");

        btnmodificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        campo_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_direccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo_IDENTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 551, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_seg_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_cel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(campocorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(combopais, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel14))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(combodpto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(combociudad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel15)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(campo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel16)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lfecha_naci, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(208, 208, 208)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(213, 213, 213)
                                            .addComponent(jLabel2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campo_pri_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campo_pri_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(campo_identificacion)
                                    .addComponent(campo_seg_apellido)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_IDENTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(campo_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(campo_pri_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campo_pri_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campo_seg_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(campo_seg_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campo_cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(campocorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(Lfecha_naci, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combopais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combodpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combociudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiar)
                    .addComponent(btncrear)
                    .addComponent(btnbuscar)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar)
                    .addComponent(btnsalir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_pri_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_pri_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_pri_apellidoActionPerformed

    private void campo_seg_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_seg_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_seg_apellidoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
       
       cargar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
   
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        String IDENTIFICACION, T_IDE, PRI_NOM, SEG_NOM, PRI_APE, SEG_APE, DIRECCION, TELFIJO, TELCELULAR, CORREO, PAIS, DEPARTAMENTO, CIUDAD;
        String sql = "";

        int dia = campo_calendario.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mes = campo_calendario.getCalendar().get(Calendar.ALL_STYLES);
        int año = campo_calendario.getCalendar().get(Calendar.YEAR);

        String FECHANACI = +año + "-" + mes + "-" + dia;

        IDENTIFICACION = campo_identificacion.getText();
        T_IDE = (String) combo_IDENTIDAD.getSelectedItem();
        PRI_NOM = campo_pri_nombre.getText();
        SEG_NOM = campo_seg_nombre.getText();
        PRI_APE = campo_pri_apellido.getText();
        SEG_APE = campo_seg_apellido.getText();
        DIRECCION = campo_direccion.getText();
        TELCELULAR = campo_cel.getText();
        TELFIJO = campo_tel.getText();
        CORREO = campocorreo.getText();
        PAIS = (String) combopais.getSelectedItem();
        DEPARTAMENTO = (String) combodpto.getSelectedItem();
        CIUDAD = (String) combociudad.getSelectedItem();

        sql = "INSERT INTO  huesped (IDENTIFICACION,TIPO_IDENTIFICACION,PRI_NOMBRE,SEG_NOMBRE,PRI_APELLIDO, SEG_APELLIDO,DIRECCION,TEL_FIJO, TEL_CELULAR,FEC_NACIMIENTO,CORREO,PAIS,DEPARTAMENTO,CIUDAD) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

        try {

            PreparedStatement pst = cn.prepareStatement(sql);

            pst.setString(1, IDENTIFICACION);
            pst.setString(2, T_IDE);
            pst.setString(3, PRI_NOM);
            pst.setString(4, SEG_NOM);
            pst.setString(5, PRI_APE);
            pst.setString(6, SEG_APE);
            pst.setString(7, DIRECCION);
            pst.setString(8, TELFIJO);
            pst.setString(9, TELCELULAR);
            pst.setString(10, FECHANACI);
            pst.setString(11, CORREO);
            pst.setString(12, PAIS);
            pst.setString(13, DEPARTAMENTO);
            pst.setString(14, CIUDAD);

            int n = pst.executeUpdate();

            if (n > 0) {
                JOptionPane.showMessageDialog(null, " Huesped Registrado ");
                limpiar();
                campo_calendario.setDate(null);
                ///ESTE CODIGO NOS PERMITE PREGUNTAR LUEGO DE CREAR UN HUESPE, SI DESEA CREAR UNA RESERVA. YES O NOI
                int respuesta = JOptionPane.showConfirmDialog(null, "=DESEA CREAR RESERVA?  " + "", "", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {

                    Reservas R = new Reservas();
                    R.setVisible(true);
                    R.setLocationRelativeTo(this);
                    R.setTitle(".....::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::SISTEMA DE RESERVAS::::::::::..............");

                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "no se pudo guardar el registro");
        }
    }//GEN-LAST:event_btncrearActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void campo_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_identificacionActionPerformed

    private void campo_seg_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_seg_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_seg_nombreActionPerformed

    private void campo_celActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_celActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_celActionPerformed

    private void campo_pri_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_pri_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_pri_nombreActionPerformed

    private void combodptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combodptoActionPerformed

    private void combociudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combociudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combociudadActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        combopais.removeAllItems();
        combodpto.removeAllItems();
        combociudad.removeAllItems();
        combo_IDENTIDAD.removeAllItems();
        buscar();

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void campo_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_telActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        String IDENTIFICACION, T_IDE, PRI_NOM, SEG_NOM, PRI_APE, SEG_APE, DIRECCION, TELFIJO, TELCELULAR, CORREO, PAIS, DEPARTAMENTO, CIUDAD;
        String sql = "";

        int dia = campo_calendario.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mes = campo_calendario.getCalendar().get(Calendar.ALL_STYLES);
        int año = campo_calendario.getCalendar().get(Calendar.YEAR);

        String FECHANACI = +año + "-" + mes + "-" + dia;

        IDENTIFICACION = campo_identificacion.getText();
        T_IDE = (String) combo_IDENTIDAD.getSelectedItem();
        PRI_NOM = campo_pri_nombre.getText();
        SEG_NOM = campo_seg_nombre.getText();
        PRI_APE = campo_pri_apellido.getText();
        SEG_APE = campo_seg_apellido.getText();
        DIRECCION = campo_direccion.getText();
        TELCELULAR = campo_cel.getText();
        TELFIJO = campo_tel.getText();
        CORREO = campocorreo.getText();
        PAIS = (String) combopais.getSelectedItem();
        DEPARTAMENTO = (String) combodpto.getSelectedItem();
        CIUDAD = (String) combociudad.getSelectedItem();

        sql = "UPDATE huesped SET TIPO_IDENTIFICACION='" + T_IDE + "',PRI_NOMBRE='" + PRI_NOM + "',SEG_NOMBRE='" + SEG_NOM + "',PRI_APELLIDO='" + PRI_APE + "', SEG_APELLIDO='" + SEG_APE + "',DIRECCION='" + DIRECCION + "',TEL_FIJO='" + TELFIJO + "', TEL_CELULAR='" + TELCELULAR + "',FEC_NACIMIENTO='" + FECHANACI + "',CORREO='" + CORREO + "',PAIS='" + PAIS + "',DEPARTAMENTO='" + DEPARTAMENTO + "',CIUDAD='" + CIUDAD + "' WHERE IDENTIFICACION=" + IDENTIFICACION;

        try {

            PreparedStatement pst = cn.prepareStatement(sql);
            int n = pst.executeUpdate();

            if (n > 0) {
                JOptionPane.showMessageDialog(null, " Huesped modificado ");

                campo_identificacion.setText("");
                campo_cel.setText("");
                campo_direccion.setText("");
                campo_pri_apellido.setText("");
                campo_seg_nombre.setText("");
                campo_pri_nombre.setText("");
                campocorreo.setText("");
                campo_cel.setText("");
                combo_IDENTIDAD.removeAllItems();
                campo_seg_apellido.setText("");
                campo_tel.setText("");
                combopais.removeAllItems();
                combodpto.removeAllItems();
                combociudad.removeAllItems();
                campo_calendario.setDate(null);


            }

        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "no se pudo EDITAR el registro");
        }

    }//GEN-LAST:event_btnmodificarActionPerformed

    public JComboBox<String> getCombociudad() {
        return combociudad;
    }

    public void setCombociudad(JComboBox<String> combociudad) {
        this.combociudad = combociudad;
    }

    public JComboBox<String> getCombodpto() {
        return combodpto;
    }

    public void setCombodpto(JComboBox<String> combodpto) {
        this.combodpto = combodpto;
    }

    public JComboBox<String> getCombopais() {
        return combopais;
    }

    public void setCombopais(JComboBox<String> combopais) {
        this.combopais = combopais;
    }

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
     
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();

        String IDENTIFICACION, T_IDE, PRI_NOM, SEG_NOM, PRI_APE, SEG_APE, DIRECCION, TELFIJO, TELCELULAR, CORREO, PAIS, DEPARTAMENTO, CIUDAD;
        String sql = "";

        IDENTIFICACION = campo_identificacion.getText();
        T_IDE = (String) combo_IDENTIDAD.getSelectedItem();
        PRI_NOM = campo_pri_nombre.getText();
        SEG_NOM = campo_seg_nombre.getText();
        PRI_APE = campo_pri_apellido.getText();
        SEG_APE = campo_seg_apellido.getText();
        DIRECCION = campo_direccion.getText();
        TELCELULAR = campo_cel.getText();
        TELFIJO = campo_tel.getText();
        CORREO = campocorreo.getText();

        int option = JOptionPane.showConfirmDialog(null,
                "Realmente desea ELIMINAR?",
                "Confirmar ELIMAR",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.YES_OPTION) {

            sql = " Delete from huesped where IDENTIFICACION = '" + IDENTIFICACION + "'";
        }

        try {

            PreparedStatement pst = cn.prepareStatement(sql);
            int n = pst.executeUpdate();

            if (n > 0) {
                JOptionPane.showMessageDialog(null, " Huesped ELIMINADO ");
                limpiar();

            }

        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Registro No Eliminado");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void campo_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_direccionActionPerformed

    private void combopaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combopaisActionPerformed
    void buscar() {
        String cc = campo_identificacion.getText();
        if (cc.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "ingrese IDENTIFICACION para la busqueda");
            campo_identificacion.requestFocus();
            return;
        }

        try {
            Connection con = null;
            String identificacion = campo_identificacion.getText();
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quick_hotel", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from  huesped where IDENTIFICACION='" + identificacion + "'  ");
             String datefecha = "";
            if (rs.next()) {
                combo_IDENTIDAD.addItem(rs.getString(2));
                campo_pri_nombre.setText(rs.getString(3));
                campo_seg_nombre.setText(rs.getString(4));
                campo_pri_apellido.setText(rs.getString(5));
                campo_seg_apellido.setText(rs.getString(6));
                campo_direccion.setText(rs.getString(7));
                campo_tel.setText(rs.getString(8));
                campo_cel.setText(rs.getString(9));
                ///JOptionPane.showMessageDialog(null, ""+rs.getString(10));
                //Lfecha_naci.setText(rs.getString(10));
                campo_calendario.setDateFormatString(rs.getString(10));
                Lfecha_naci.setText(rs.getString(10));
                campocorreo.setText(rs.getString(11));
                combopais.addItem(rs.getString(12));
                combodpto.addItem(rs.getString(13));
                combociudad.addItem(rs.getString(14));

            } else {
                JOptionPane.showMessageDialog(null, "no se encontro registro con identificacion : " + campo_identificacion.getText());

                int option = JOptionPane.showConfirmDialog(null,
                        "Desea Crear Huesped ?",
                         "Confirmar ",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (option == JOptionPane.YES_OPTION) {
                    campo_pri_nombre.requestFocus();
                }
            }
        } catch (Exception e) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, e);
        }

    }

    public void setCalendario(JDateChooser calendario) {
        this.campo_calendario = calendario;
    }

   public static void  cargar() {
        try {
            Connection con = null;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quick_hotel", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from INFORMACION ");
            
            while (rs.next()) {
                combopais.addItem(rs.getString(1));
                combodpto.addItem(rs.getString(2));
                combociudad.addItem(rs.getString(3));
                

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    void limpiar() {
        campo_identificacion.setText("");
        campo_cel.setText("");
        campo_direccion.setText("");
        campo_pri_apellido.setText("");
        campo_seg_nombre.setText("");
        campo_pri_nombre.setText("");
        campocorreo.setText("");
        campo_cel.setText("");
        combo_IDENTIDAD.setSelectedIndex(0);
        campo_seg_apellido.setText("");
        campo_tel.setText("");
        combopais.setSelectedIndex(0);
        combodpto.setSelectedIndex(0);
        combociudad.setSelectedIndex(0);
        campo_calendario.setDateFormatString(clave);

    }

    public static JDateChooser getCampo_calendario() {
        return campo_calendario;
    }

    public static void setCampo_calendario(JDateChooser campo_calendario) {
        Registro.campo_calendario = campo_calendario;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lfecha_naci;
    public static javax.swing.JButton btnbuscar;
    public static javax.swing.JButton btncrear;
    public static javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    public static javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    public static com.toedter.calendar.JDateChooser campo_calendario;
    public static javax.swing.JTextField campo_cel;
    public static javax.swing.JTextField campo_direccion;
    public static javax.swing.JTextField campo_identificacion;
    public static javax.swing.JTextField campo_pri_apellido;
    public static javax.swing.JTextField campo_pri_nombre;
    public static javax.swing.JTextField campo_seg_apellido;
    public static javax.swing.JTextField campo_seg_nombre;
    public static javax.swing.JTextField campo_tel;
    public static javax.swing.JTextField campocorreo;
    public static javax.swing.JComboBox<String> combo_IDENTIDAD;
    public static javax.swing.JComboBox<String> combociudad;
    public static javax.swing.JComboBox<String> combodpto;
    public static javax.swing.JComboBox<String> combopais;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
